version: "3.9"

services:
  cockroach:
    image: cockroachdb/cockroach:v23.1.11
    command: start-single-node --insecure --listen-addr=0.0.0.0:26257 --http-addr=0.0.0.0:8085 --advertise-addr=cockroach:26257 --store=/cockroach/cockroach-data
    ports:
      - "26258:26257"
      - "8085:8085"
    volumes:
      - astraxis_db_data:/cockroach/cockroach-data

  redis:
    image: redis:7

  backend:
    image: ghcr.io/rangedace/astraxis:latest
    environment:
      ROLE: backend
      PORT: 3001
      DATABASE_URL: postgresql://root@cockroach:26257/astraxis?sslmode=disable
      JWT_SECRET: change_me_secret
      JWT_REFRESH_SECRET: change_me_refresh
      REDIS_URL: redis://redis:6379
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - cockroach
      - redis
    ports:
      - "3001:3001"

  frontend:
    image: ghcr.io/rangedace/astraxis:latest
    environment:
      ROLE: frontend
      PORT: 3000
      NEXT_PUBLIC_API_URL: http://localhost:3001/api
    depends_on:
      - backend
    ports:
      - "32601:3000"

volumes:
  astraxis_db_data:
